let phonesList = [
    {
        "id":  "3d7584c3-2ae5-4fce-98b8-9b4b9bf98888",
        "name": "Xiaomi Mi 11 Ultra",
        "manufacturer": "Xiaomi",
        "description": "Fingerprint (under display, optical), accelerometer, gyro, proximity, compass, color spectrum",
        "color": "Ceramic White, Ceramic Black",
        "price": "1200 EUR",
        "imageFileName":"https://cdn-files.kimovil.com/default/0005/89/thumb_488011_default_big.jpeg",
        "screen": "6.81",
        "resolution": "1440x3200 px",
        "processor": "Qualcomm Snapdragon 888",
        "ram": "256GB 8GB RAM, 256GB 12GB RAM, 512GB 12GB RAM",
        "weight": "234 g",
        "memory": "256 GB",
        "cam": "50MP"
    },
    {
        "id":  "3d7584c3-2ae5-4fce-98b8-9b4b9bf95656",
        "name": "Xiaomi Poco F3",
        "manufacturer": "Xiaomi",
        "description": "Fingerprint (side-mounted), accelerometer, gyro, proximity, compass, color spectrum",
        "color": "Ceramic White, Ceramic Black",
        "price": "300 EUR",
        "imageFileName":"https://cdn-files.kimovil.com/phone_front/0005/86/thumb_485001_phone_front_big.jpeg",
        "screen": "6.67",
        "resolution": "1080x2400 px",
        "processor": "Qualcomm Snapdragon 870",
        "ram": "128GB, 256GB",
        "weight": "196 g",
        "memory": "128 GB",
        "cam": "48MP"
       },
       {
        "id":  "3d7584c3-2ae5-4fce-98b8-9b4b9bf92525",
        "name": "Nokia X20",
        "manufacturer": "Nokia",
        "description": "Fingerprint (side-mounted), accelerometer, gyro, proximity",
        "color": "Midnight Sun, Nordic Blue",
        "price": "350 EUR",
        "imageFileName":"https://fdn2.gsmarena.com/vv/pics/nokia/nokia-x20-1.jpg",
        "screen": "6.67",
        "resolution": "1080x2400 px",
        "processor": "Qualcomm Snapdragon 870",
        "ram": "6 GB, 8 GB",
        "weight": "220 g",
        "memory": "128 GB",
        "cam": "48MP"
       },
       {
        "id":  "3d7584c3-2ae5-4fce-98b8-9b4b9bf9koko4",
        "name": "Xiaomi Redmi K40 Pro",
        "manufacturer": "Xiaomi",
        "description": "Fingerprint (side-mounted), accelerometer, gyro, proximity, compass, color spectrum, barometer",
        "color": "Black, White, Aurora",
        "price": "443 EUR",
        "imageFileName":"https://cdn-files.kimovil.com/default/0005/77/thumb_476327_default_big.jpeg",
        "screen": "6.67",
        "resolution": "1080x2400 px",
        "processor": "Qualcomm Snapdragon 888",
        "ram": "6 GB",
        "weight": "197 g",
        "memory": "128 GB",
        "cam": "64MP"
       },
       {
        "id":  "3d7584c3-2ae5-4fce-98b8-9b4b9bf97777",
        "name": "OnePlus 8T",
        "manufacturer": "OnePlus",
        "description": "Fingerprint (under display, optical), accelerometer, gyro, proximity, compass, barometer (market dependant)",
        "color": "Aquamarine Green, Lunar Silver, Cyberpunk 2077 Edition",
        "price": "455 EUR",
        "imageFileName":"https://cdn-files.kimovil.com/default/0005/28/thumb_427558_default_big.jpeg",
        "screen": "6.55",
        "resolution": "	1080 x 2400 px",
        "processor": "Qualcomm Snapdragon 865",
        "ram": "8 GB",
        "weight": "188 g",
        "memory": "128 GB",
        "cam": "48MP"
       },
       {
        "id":  "3d7584c3-2ae5-4fce-98b8-9b4b9bf92020a",
        "name": "Samsung Galaxy M62",
        "manufacturer": "Samsung",
        "description": "Fingerprint (side-mounted), accelerometer, gyro, proximity, compass",
        "color": "Laser Green, Laser Gray, Laser Blue",
        "price": "339 EUR",
        "imageFileName":"https://cdn-files.kimovil.com/default/0005/88/thumb_487906_default_big.jpeg",
        "screen": "6.7",
        "resolution": "1080 x 2400 px",
        "processor": "Samsung Exynos 9 9825",
        "ram": "8 GB",
        "weight": "218 g",
        "memory": "128 GB",
        "cam": "64MP"
       },
       {
        "id":  "3d7584c3-2ae5-4fce-98b8-9b4b9bf9jiji",
        "name": "Nubia Red Magic 6",
        "manufacturer": "Nubia",
        "description": "Fingerprint (side-mounted), accelerometer, gyro, proximity, compass",
        "color": "Laser Green, Laser Gray, Laser Blue",
        "price": "339 EUR",
        "imageFileName":"https://cdn-files.kimovil.com/default/0005/79/thumb_478990_default_big.jpeg",
        "screen": "6.8",
        "resolution": "1080 x 2400 px",
        "processor": "Qualcomm Snapdragon 888",
        "ram": "16 GB",
        "weight": "220 g",
        "memory": "256 GB",
        "cam": "64MP"
       },
       {
        "id":  "3d7584c3-2ae5-4fce-98b8-9b4b9bf9huhu",
        "name": "Huawei Mate 40 Pro",
        "manufacturer": "Huawei",
        "description": "Face ID, fingerprint (under display, optical), accelerometer, gyro, proximity, barometer, compass, color spectrum",
        "color": "Mystic Silver, White, Black, Green, Yellow",
        "price": "339 EUR",
        "imageFileName":"https://cdn-files.kimovil.com/default/0005/30/thumb_429987_default_big.jpeg",
        "screen": "6.76",
        "resolution": "1344 x 2772 px",
        "processor": "Huawei HiSilicon KIRIN 9000",
        "ram": "8 GB",
        "weight": "212 g",
        "memory": "256 GB",
        "cam": "13MP"
       },
       {
        "id":  "3d7584c3-2ae5-4fce-98b8-9b4b9bf95s43",
        "name": "Black Shark 4",
        "manufacturer": "Xiaomi",
        "description": "Fingerprint (side-mounted), accelerometer, gyro, proximity, compass, barometer",
        "color": "Magic Black, Black, Blue, Silver",
        "price": "383 EUR",
        "imageFileName":"https://cdn-files.kimovil.com/default/0005/86/thumb_485582_default_big.jpeg",
        "screen": "6.67",
        "resolution": "1080 x 2400 px",
        "processor": "Qualcomm Snapdragon 870",
        "ram": "6 GB",
        "weight": "210 g",
        "memory": "128 GB, 256 GB",
        "cam": "48MP"
       },
       {
        "id":  "3d7584c3-2ae5-4fce-98b8-9b4b9bf9js2gtl",
        "name": "Vivo X60 Pro",
        "manufacturer": "Vivo",
        "description": "Fingerprint (under display, optical), accelerometer, gyro, proximity, compass, color spectrum",
        "color": "Midnight Black, Shimmer Blue",
        "price": "593 EUR",
        "imageFileName":"https://cdn-files.kimovil.com/default/0005/52/thumb_451987_default_big.jpeg",
        "screen": "6.57",
        "resolution": "1080 x 2376 px",
        "processor": "Samsung Exynos 1080",
        "ram": "12 GB",
        "weight": "178 g",
        "memory": "256 GB",
        "cam": "48MP"
       },
       {
        "id":  "3d7584c3-2ae5-4fce-98b8-9b4b9bf9juhb32",
        "name": "Samsung Galaxy S20 FE",
        "manufacturer": "Samsung",
        "description": "Fingerprint (under display, optical), accelerometer, gyro, proximity, compass, Bixby natural language commands and dictation,Samsung Pay (Visa, MasterCard certified)",
        "color": "Cloud Lavender, Cloud Mint, Cloud Navy, Cloud White, Cloud Red, Cloud Orange",
        "price": "435 EUR",
        "imageFileName":"https://cdn-files.kimovil.com/default/0005/20/thumb_419891_default_big.jpeg",
        "screen": "6.5",
        "resolution": "1080 x 2400 px",
        "processor": "Samsung Exynos 990",
        "ram": "6 GB",
        "weight": "190 g",
        "memory": "128 GB",
        "cam": "12MP"
       },
       {
        "id":  "3d7584c3-2ae5-4fce-98b8-9b4b9bf9lkjlkjklj",
        "name": "Asus ROG Phone 3 Strix Edition",
        "manufacturer": "Asus",
        "description": "Fingerprint (under display, optical), accelerometer, gyro, proximity, compass",
        "color": "Black Glare",
        "price": "610 EUR",
        "imageFileName":"https://fdn2.gsmarena.com/vv/bigpic/asus-rog-phone3-strix.jpg",
        "screen": "6.59",
        "resolution": "1080 x 2340 px",
        "processor": "Qualcomm Snapdragon 865",
        "ram": "16 GB",
        "weight": "240 g",
        "memory": "512 GB",
        "cam": "64MP"
       },
       {
        "id":  "3d7584c3-2ae5-4fce-98b8-9b4b9bf9jklhkj74",
        "name": "Motorola Edge+",
        "manufacturer": "Motorola",
        "description": "Fingerprint (under display, optical), accelerometer, gyro, proximity, compass, barometer",
        "color": "Smokey Sangria, Thunder Grey, Baltic Gray",
        "price": "645 EUR",
        "imageFileName":"https://fdn2.gsmarena.com/vv/bigpic/motorola-edge-plus.jpg",
        "screen": "6.67",
        "resolution": "1080 x 2340 px",
        "processor": "Qualcomm Snapdragon 865",
        "ram": "12 GB",
        "weight": "203 g",
        "memory": "256 GB",
        "cam": "108MP"
       },
       {
        "id":  "3d7584c3-2ae5-4fce-98b8-9b4b9bf945chs",
        "name": "Apple iPhone 11",
        "manufacturer": "Apple",
        "description": "Face ID, accelerometer, gyro, proximity, compass, barometer, Siri natural language commands and dictation, Ultra Wideband (UWB) support",
        "color": "Black, Green, Yellow, Purple, Red, White",
        "price": "569 EUR",
        "imageFileName":"https://cdn-files.kimovil.com/default/0003/49/thumb_248672_default_big.jpeg",
        "screen": "6.1",
        "resolution": "828 x 1792 px",
        "processor": "Apple A13 Bionic",
        "ram": "4 GB",
        "weight": "203 g",
        "memory": "64 GB, 128 GB 256 GB",
        "cam": "12MP"
       },
       {
        "id":  "3d7584c3-2ae5-4fce-98b8-9b4b9bf932323243",
        "name": "Vivo iQOO Neo5",
        "manufacturer": "Vivo",
        "description": "Fingerprint (under display, optical), accelerometer, gyro, proximity, compass",
        "color": "Black, Blue, Orange",
        "price": "395 EUR",
        "imageFileName":"https://fdn2.gsmarena.com/vv/bigpic/vivo-iqoo-neo5.jpg",
        "screen": "6.62",
        "resolution": "1080 x 2400 px",
        "processor": "Qualcomm Snapdragon 870",
        "ram": "8 GB",
        "weight": "203 g",
        "memory": "128 GB",
        "cam": "48MP"
       },
       {
        "id":  "3d7584c3-2ae5-4fce-98b8-9b4b9bf9sasa65",
        "name": "iPhone SE (2020)",
        "manufacturer": "Apple",
        "description": "Fingerprint (front-mounted), accelerometer, proximity, gyro, compass, barometer, fast charging 18W, 50% in 30 min (advertised)  Qi wireless charging",
        "color": "Black, White, Red",
        "price": "374 EUR",
        "imageFileName":"https://cdn-files.kimovil.com/default/0004/52/thumb_351846_default_big.jpeg",
        "screen": "4.7",
        "resolution": "750 x 1334 px",
        "processor": "Apple A13 Bionic",
        "ram": "3 GB",
        "weight": "203 g",
        "memory": "64GB, 128GB, 256GB",
        "cam": "12MP"
       },
  ]
  

  module.exports = phonesList;